#!/usr/bin/env python3
"""Generate the Learner Guide DOCX (courseware/LG-*.docx).


House format: cover page, Document Version Control Record, auto TOC, Arial 11pt
body, one section per lab (Objective · Goal · What you'll build · Step-by-step
with commands · Test it), plus setup, exam-prep and glossary. All content is
driven by course_data + the domain data files, keeping the LG 100% aligned with
the slide deck, Lesson Plan and labs.
"""
import os, sys
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

HERE=os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0,HERE)
import course_data as C
from data_topic1 import TOPIC1; from data_topic2 import TOPIC2
from data_topic3 import TOPIC3; from data_topic4 import TOPIC4
from data_topic5 import TOPIC5
ACT=TOPIC1+TOPIC2+TOPIC3+TOPIC4+TOPIC5
import prodoc
REPO=HERE; ASSETS=os.path.join(REPO,"courseware","assets")

# ---------------- block DSL (single content stream → MD + DOCX) ----------------
B=[]
def h1(t): B.append(("h1",t))
def h2(t): B.append(("h2",t))
def h3(t): B.append(("h3",t))
def p(t):  B.append(("p",t))
def bullets(xs): B.append(("bullets",xs))
def steps(xs): B.append(("steps",xs))
def code(t): B.append(("code",t))
def note(t): B.append(("note",t))
def rule(): B.append(("rule",))

# ---------------- content ----------------
h1("Introduction")
p(f"This Learner Guide accompanies the WSQ course {C.TITLE} ({C.COURSE_CODE}), conducted by {C.ORG}. "
  f"It provides step-by-step instructions for all {len(ACT)} hands-on labs, organised by the five "
  "course topics. Every lab builds part of one real application: CardGuard, a card-transaction "
  "fraud screening system written in Python with the help of an AI coding assistant.")
p("Use this guide alongside the course slides and the lab files in the labs/ folder of the course "
  "repository. Every lab runs locally with uv — there is no cloud account to create and nothing to "
  "pay for. The combined notebook labs/CardGuard-All-Labs.ipynb contains every step in one file.")

h1("Course Learning Outcomes")
bullets(C.LEARNING_OUTCOMES)

h1("Before You Start — Environment Setup")
h3("What you need")
bullets([
 "A laptop running macOS, Windows or Linux with a terminal.",
 "uv — the Python project and package manager used by every lab (it installs Python for you).",
 "An AI coding assistant: Claude, GitHub Copilot or Cursor.",
 "A code editor such as Visual Studio Code.",
 "Docker Desktop — required only for the Topic 5 deployment labs.",
])
h3("Install uv and create your first project")
p("uv installs and manages the Python interpreter, the virtual environment and a lockfile. You never "
  "activate a virtual environment by hand — prefix commands with uv run and uv does it for you.")
code("# macOS / Linux\ncurl -LsSf https://astral.sh/uv/install.sh | sh\n\n# Windows (PowerShell)\npowershell -c \"irm https://astral.sh/uv/install.ps1 | iex\"\n\nuv --version           # confirm the install\nuv init cardguard      # create the course project\ncd cardguard\nuv python pin 3.12     # everyone runs the same interpreter\nuv add pandas pydantic fastapi 'uvicorn[standard]' streamlit httpx pytest\nuv run python mockdata.py    # generate the deterministic dataset")
h3("Conventions used in every lab")
bullets([
 "Every lab runs inside the cardguard project — labs build on each other, so keep the folder.",
 "Commands are prefixed with uv run; you never activate a virtual environment by hand.",
 "Blocks starting with a filename comment (e.g. # models.py) are files to create or edit.",
 "Prompts you give the AI assistant are shown as quoted text, not as code.",
 "The dataset is generated by mockdata.py with a fixed seed — everyone sees identical numbers.",
 "Each lab ends with a Test it step; do not move on until it passes.",
])

# ---------------- per-topic, per-lab ----------------
TOPICS_BY_NUM={t["num"]:t for t in C.TOPICS}
for t in C.TOPICS:
    h1(f"Topic {t['code']} — {t['title']}")
    p(t["subtitle"])
    h3("Key concepts")
    bullets(t["concepts"])
    for a in [x for x in ACT if x["topic"]==t["num"]]:
        h2(f"Lab {a['num']} — {a['title']}")
        p(f"Objective: {a['objective']}.")
        p(f"Goal: {a['desc']}")
        h3("What you'll build")
        p(a["build"]+f"   (Tools & libraries: {a['services']}.)")
        h3("Step-by-step")
        st=[]
        for i,(instr,cmd) in enumerate([(s[0], s[1] if len(s)>1 else "") if isinstance(s,(tuple,list)) else (s,"") for s in a["steps"]],1):
            st.append((instr,cmd))
        steps(st)
        h3("Test it")
        p(a["test"])
        note(f"The full lab — README, Python files and a replayable commands.sh — is in "
             f"labs/topic{a['topic']}/lab{a['num']:02d}_*/. Every step is also a cell in "
             f"labs/CardGuard-All-Labs.ipynb.")
        rule()

h1("Quick Command Reference")
qr=[
 ("uv init <folder>","Create a new Python project with pyproject.toml."),
 ("uv python pin 3.12","Pin the interpreter so every machine runs the same Python."),
 ("uv add <package>","Resolve, install and record a dependency in uv.lock."),
 ("uv add --dev pytest","Add a development-only dependency."),
 ("uv run python main.py","Run a script inside the project environment (no venv activation)."),
 ("uv sync","Recreate .venv exactly from uv.lock."),
 ("uv lock --check","Verify the lockfile is current before committing or building."),
 ("uv run pytest -v","Run the test suite."),
 ("uv run uvicorn main:app --reload","Start the FastAPI service on http://127.0.0.1:8000."),
 ("uv run streamlit run app.py","Start the Streamlit dashboard on http://localhost:8501."),
 ("curl http://127.0.0.1:8000/health","Check the API is alive."),
 ("http://127.0.0.1:8000/docs","Open the auto-generated OpenAPI documentation."),
 ("docker build -t cardguard-api:1.0 .","Build the container image."),
 ("docker compose up --build -d","Start the API and UI together."),
 ("docker compose ps","Show service status and health."),
 ("docker compose logs api --tail 20","Read the API container logs."),
 ("docker compose down","Stop the stack (named volumes are kept)."),
 ("git check-ignore -v .env","Confirm secrets are excluded before committing."),
]
B.append(("dl",qr))

h1("Glossary")
gl=[
 ("uv","A fast Python project manager handling the interpreter, virtual environment and lockfile."),
 ("uv.lock","The file pinning exact dependency versions so installs are reproducible."),
 ("Vibe coding","Directing an AI assistant to write code that you specify, review, test and own."),
 ("Class / object","A class bundles data with behaviour; an object is one instance of that class."),
 ("Encapsulation","Hiding internal state behind methods and properties so callers depend on behaviour."),
 ("Inheritance","Deriving a class from a base class to share behaviour ('is-a')."),
 ("Composition","Building an object from other objects it holds ('has-a') — usually the better default."),
 ("Dunder method","A double-underscore method such as __init__ or __repr__ that hooks into Python syntax."),
 ("Exception","An error raised at runtime; caught with try/except and cleaned up with finally."),
 ("DataFrame","pandas' labelled two-dimensional table; a single column is a Series."),
 ("split-apply-combine","The groupby-then-aggregate pattern that answers most analytics questions."),
 ("Copy-on-Write","pandas 3.0 default — chained assignment no longer mutates the original frame."),
 ("Pydantic model","A class declaring data shape with type hints and validating it at runtime."),
 ("FastAPI","A framework turning typed Python functions into HTTP endpoints with automatic docs."),
 ("Streamlit","A framework for building data application UIs in pure Python."),
 ("SQLite","A file-based SQL database built into Python — no server required."),
 ("Container image","Interpreter, dependencies and code packaged into one deployable artifact."),
 ("Health check","An endpoint a platform polls to confirm a service is alive and ready."),
]
B.append(("dl",gl))

h1("Support")
p(f"Courseware and the assessment are on the Tertiary Infotech LMS: https://lms-tms.tertiaryinfotech.com/")
bullets([
 f"{C.ORG} ({C.UEN})",
 "Email: enquiry@tertiaryinfotech.com",
 "Phone: +65 6100 0613",
 "Website: www.tertiarycourses.com.sg",
])
h3("Assessment Flow")
p("On assessment day, follow this order:")
bullets([
 "TRAQOM — scan the TRAQOM QR code on the LMS and complete the survey.",
 "Assessment Digital Attendance — scan the SSG QR code.",
 "Assessment — Written Assessment (SAQ) followed by a Case Study (CS), open book.",
 "Submit your assessment answers on the LMS.",
 "Sign the Assessment Summary Record.",
])
p(C.ASSESSMENT["note"])

# ---------------- render Markdown ----------------
def _anchor(txt):
    return "".join(ch.lower() if ch.isalnum() else ("-" if ch in " -" else "") for ch in txt)

def render_md():
    out=[f"# {C.TITLE} — Learner Guide",""]
    out.append(f"**WSQ Course Code:** {C.COURSE_CODE}  |  **Conducted by:** {C.ORG} ({C.UEN.replace('UEN: ','UEN ')})  |  **Version {C.VERSION} · {C.VERSION_DATE}**")
    out.append("")
    # TOC (h1 + h2)
    out.append("## Contents"); out.append("")
    for kind,*rest in B:
        if kind=="h1": out.append(f"- [{rest[0]}](#{_anchor(rest[0])})")
        elif kind=="h2": out.append(f"  - [{rest[0]}](#{_anchor(rest[0])})")
    out.append("")
    for kind,*rest in B:
        if kind=="h1": out+=["",f"## {rest[0]}",""]
        elif kind=="h2": out+=["",f"### {rest[0]}",""]
        elif kind=="h3": out+=[f"**{rest[0]}**",""]
        elif kind=="p": out+=[rest[0],""]
        elif kind=="bullets": out+=[f"- {x}" for x in rest[0]]+[""]
        elif kind=="steps":
            for i,(instr,cmd) in enumerate(rest[0],1):
                out.append(f"{i}. {instr}")
                if cmd: out+=["",f"   ```bash",f"   {cmd}","   ```",""]
            out.append("")
        elif kind=="code": out+=["```bash",rest[0],"```",""]
        elif kind=="note": out+=[f"> **Note:** {rest[0]}",""]
        elif kind=="rule": out+=["---",""]
        elif kind=="dl":
            for term,defn in rest[0]: out.append(f"- **{term}** — {defn}")
            out.append("")
    return "\n".join(out)

MD_OUT=os.path.join(REPO,f"LG-{C.SHORT_TITLE}.md")
with open(MD_OUT,"w") as f: f.write(render_md())
print("Saved",MD_OUT)

# ---------------- render DOCX ----------------
BRAND=RGBColor(0x1F,0x6F,0xEB); DARK=RGBColor(0x11,0x18,0x27); GREY=RGBColor(0x55,0x5B,0x66)
INKCODE=RGBColor(0x0B,0x30,0x60)
doc=Document()
normal=doc.styles["Normal"]; normal.font.name="Arial"; normal.font.size=Pt(11)
prodoc.style_headings(doc)
prodoc.add_cover_page(doc,"LEARNER GUIDE",C.TITLE,C.VERSION.lstrip("v"),
                      org_logo=os.path.join(ASSETS,"tertiary-infotech-logo.png"),
                      course_logo=None, course_code=C.COURSE_CODE)
prodoc.add_version_control(doc,C.VERSIONS)
prodoc.add_toc(doc)

def code_para(text):
    for line in text.split("\n"):
        para=doc.add_paragraph(); prodoc._shade_para(para) if hasattr(prodoc,"_shade_para") else None
        r=para.add_run(line); r.font.name="Consolas"; r.font.size=Pt(9.5); r.font.color.rgb=INKCODE

for kind,*rest in B:
    if kind=="h1": doc.add_heading(rest[0],level=1)
    elif kind=="h2": doc.add_heading(rest[0],level=2)
    elif kind=="h3":
        para=doc.add_paragraph(); r=para.add_run(rest[0]); r.bold=True; r.font.size=Pt(11); r.font.color.rgb=BRAND
    elif kind=="p": doc.add_paragraph(rest[0])
    elif kind=="bullets":
        for x in rest[0]: doc.add_paragraph(x,style="List Bullet")
    elif kind=="steps":
        for i,(instr,cmd) in enumerate(rest[0],1):
            para=doc.add_paragraph(style="List Number"); para.add_run(instr)
            if cmd: code_para(cmd)
    elif kind=="code": code_para(rest[0])
    elif kind=="note":
        para=doc.add_paragraph(); r=para.add_run("Note: "); r.bold=True; r.font.color.rgb=BRAND
        para.add_run(rest[0]).font.size=Pt(10)
    elif kind=="rule": doc.add_paragraph("")
    elif kind=="dl":
        for term,defn in rest[0]:
            para=doc.add_paragraph(style="List Bullet")
            r=para.add_run(term+" — "); r.bold=True; para.add_run(defn)

prodoc.add_page_numbers(doc)
prodoc.enable_update_fields(doc)
DOCX_OUT=os.path.join(REPO,"courseware",f"LG-{C.SHORT_TITLE}.docx")
doc.save(DOCX_OUT)
print("Saved",DOCX_OUT)
