"""
TOPIC 2 — Object-Oriented Programming in Python
Classes · Encapsulation · Inheritance · Composition · Dunder Methods

Domain: CardGuard, a card-transaction fraud screening system.
All labs run on uv against the deterministic cardguard.db from mockdata.py.
"""

TOPIC2 = [
    dict(
        num=5,
        topic=2,
        title="Model a Domain with Classes and Dunder Methods",
        objective="Define classes that bundle data with behaviour",
        desc="The learner replaces loose dictionaries with a Transaction class, adds __init__, __repr__ and __eq__, and sees why a class is easier to reason about than a dict once behaviour is attached to the data.",
        build="A Transaction class with construction, printing, equality and derived properties",
        services="uv, Python 3.12, dataclasses, sqlite3",
        steps=[
            ("Start the project and generate the database", "uv init cardguard\ncd cardguard\nuv add pandas\ncp ../mockdata.py .\nuv run python mockdata.py"),
            ("Look at the raw shape of the data you are about to model",
             'uv run python -c "\nimport sqlite3\ncon = sqlite3.connect(\'cardguard.db\')\nrow = con.execute(\'SELECT * FROM transactions LIMIT 1\').fetchone()\nprint(row)\n"'),
            ("Write the Transaction class — data and the behaviour that belongs with it",
             '# models.py\nfrom dataclasses import dataclass\nfrom datetime import datetime\n\n@dataclass\nclass Transaction:\n    """One card transaction presented for screening."""\n    id: int\n    card_ref: str\n    ts: datetime\n    amount: float\n    merchant_category: str\n    city: str\n    lat: float\n    lon: float\n\n    @property\n    def hour(self) -> int:\n        """Hour of day, 0-23 — used by the unusual-hour rule."""\n        return self.ts.hour\n\n    @property\n    def is_high_risk_category(self) -> bool:\n        return self.merchant_category in {"crypto_exchange", "gift_cards", "jewellery"}\n\n    def __repr__(self) -> str:\n        return (f"Transaction(id={self.id}, card={self.card_ref}, "\n                f"${self.amount:,.2f}, {self.merchant_category}, {self.city})")'),
            ("Add a constructor that builds a Transaction from a database row",
             '    @classmethod\n    def from_row(cls, row: tuple) -> "Transaction":\n        """Build a Transaction from a sqlite row tuple."""\n        return cls(id=row[0], card_ref=row[1], ts=datetime.fromisoformat(row[2]),\n                   amount=row[3], merchant_category=row[4], city=row[5],\n                   lat=row[6], lon=row[7])'),
            ("Load real rows through the class and print them",
             'uv run python -c "\nimport sqlite3\nfrom models import Transaction\ncon = sqlite3.connect(\'cardguard.db\')\nrows = con.execute(\'SELECT * FROM transactions LIMIT 5\').fetchall()\nfor r in rows:\n    t = Transaction.from_row(r)\n    print(t, \'| hour\', t.hour, \'| high risk\', t.is_high_risk_category)\n"'),
            ("Verify @dataclass gave you equality for free — dicts compare by content, objects normally by identity",
             'uv run python -c "\nfrom datetime import datetime\nfrom models import Transaction\na = Transaction(1, \'CH0001\', datetime(2026,4,1,9), 50.0, \'grocery\', \'Singapore\', 1.35, 103.8)\nb = Transaction(1, \'CH0001\', datetime(2026,4,1,9), 50.0, \'grocery\', \'Singapore\', 1.35, 103.8)\nprint(\'equal:\', a == b)\nprint(\'same object:\', a is b)\n"'),
            ("Note the gain: hour and is_high_risk_category live WITH the data. With dicts, that logic would be scattered across every caller."),
        ],
        test="Transaction.from_row builds objects from the database, __repr__ prints readably, __eq__ compares by value, and the derived properties return correct results.",
    ),
    dict(
        num=6,
        topic=2,
        title="Encapsulate State with Properties and Validation",
        objective="Protect object state behind a controlled interface",
        desc="The learner builds a Cardholder class whose running spend baseline cannot be corrupted from outside, using private attributes, a read-only property and validation in the setter.",
        build="A Cardholder class with a protected baseline and a validated update method",
        services="uv, Python 3.12",
        steps=[
            ("Write the class with state deliberately kept private",
             '# cardholder.py\nclass Cardholder:\n    """A card account with a running spend baseline used for anomaly scoring."""\n\n    def __init__(self, card_ref: str, name: str, home_city: str, typical_amount: float):\n        if typical_amount <= 0:\n            raise ValueError("typical_amount must be positive")\n        self.card_ref = card_ref\n        self.name = name\n        self.home_city = home_city\n        self._typical_amount = typical_amount   # leading _ = internal\n        self._observed_count = 0\n\n    @property\n    def typical_amount(self) -> float:\n        """Read-only view of the baseline — callers cannot assign to it."""\n        return round(self._typical_amount, 2)\n\n    @property\n    def observed_count(self) -> int:\n        return self._observed_count'),
            ("Add the only sanctioned way to move the baseline",
             '    def observe(self, amount: float) -> None:\n        """Fold one new transaction into the running baseline."""\n        if amount < 0:\n            raise ValueError("amount must not be negative")\n        self._observed_count += 1\n        weight = 1 / min(self._observed_count, 30)   # rolling, recency-weighted\n        self._typical_amount = (1 - weight) * self._typical_amount + weight * amount\n\n    def deviation_factor(self, amount: float) -> float:\n        """How many times the baseline this amount represents."""\n        return round(amount / self._typical_amount, 2)'),
            ("Prove the baseline cannot be overwritten from outside",
             'uv run python -c "\nfrom cardholder import Cardholder\nch = Cardholder(\'CH0001\', \'Aisha Tan\', \'Singapore\', 120.0)\ntry:\n    ch.typical_amount = 999999\nexcept AttributeError as e:\n    print(\'blocked:\', e)\n"'),
            ("Drive the baseline the sanctioned way and watch it move",
             'uv run python -c "\nfrom cardholder import Cardholder\nch = Cardholder(\'CH0001\', \'Aisha Tan\', \'Singapore\', 120.0)\nfor amt in [110, 130, 125, 118, 122]:\n    ch.observe(amt)\nprint(\'baseline\', ch.typical_amount, \'after\', ch.observed_count, \'observations\')\nprint(\'a $2,400 charge is\', ch.deviation_factor(2400), \'x baseline\')\n"'),
            ("Confirm validation rejects bad input at both entry points",
             'uv run python -c "\nfrom cardholder import Cardholder\nfor bad in [lambda: Cardholder(\'C\',\'n\',\'SG\',0), lambda: Cardholder(\'C\',\'n\',\'SG\',120).observe(-5)]:\n    try:\n        bad(); print(\'NOT CAUGHT\')\n    except ValueError as e:\n        print(\'correctly raised:\', e)\n"'),
            ("Load the real cardholders and rank them by baseline",
             'uv run python -c "\nimport sqlite3\nfrom cardholder import Cardholder\ncon = sqlite3.connect(\'cardguard.db\')\nrows = con.execute(\'SELECT card_ref,name,home_city,typical_amount FROM cardholders\').fetchall()\nchs = [Cardholder(*r) for r in rows]\ntop = sorted(chs, key=lambda c: c.typical_amount, reverse=True)[:5]\nfor c in top:\n    print(f\'{c.card_ref} {c.name:<16} baseline ${c.typical_amount:,.2f}\')\n"'),
            ("Note why this matters for fraud: if any caller could assign typical_amount directly, an attacker-controlled input path could raise the baseline until nothing looks anomalous."),
        ],
        test="Assigning to typical_amount raises AttributeError; observe() updates the baseline; both constructors and observe() reject invalid values; the 5 highest baselines print from the database.",
    ),
    dict(
        num=7,
        topic=2,
        title="Build a Rule Hierarchy with Inheritance and Polymorphism",
        objective="Share behaviour through a base class and override it per rule",
        desc="The learner defines an abstract FraudRule base class and implements four concrete rules. Each rule scores a transaction differently but presents an identical interface, so the caller never needs to know which rule it holds.",
        build="An abstract FraudRule plus AmountDeviationRule, UnusualHourRule, HighRiskCategoryRule and VelocityRule",
        services="uv, Python 3.12, abc",
        steps=[
            ("Define the contract every rule must satisfy",
             '# rules.py\nfrom abc import ABC, abstractmethod\nfrom dataclasses import dataclass\nfrom models import Transaction\nfrom cardholder import Cardholder\n\n@dataclass\nclass RuleResult:\n    """One rule\'s verdict on one transaction."""\n    rule_name: str\n    score: float          # 0.0 (clean) .. 1.0 (certain)\n    reason: str\n\nclass FraudRule(ABC):\n    """Base class: every rule scores a transaction from 0.0 to 1.0."""\n\n    weight: float = 1.0\n\n    @property\n    def name(self) -> str:\n        return self.__class__.__name__\n\n    @abstractmethod\n    def score(self, txn: Transaction, holder: Cardholder,\n              history: list[Transaction]) -> RuleResult:\n        """Return this rule\'s verdict. Must be implemented by every subclass."""'),
            ("Prove the abstract class cannot be instantiated — the contract is enforced",
             'uv run python -c "\nfrom rules import FraudRule\ntry:\n    FraudRule()\nexcept TypeError as e:\n    print(\'correctly blocked:\', e)\n"'),
            ("Implement the amount-deviation rule",
             'class AmountDeviationRule(FraudRule):\n    """Flags spend far above this cardholder\'s own baseline."""\n    weight = 1.2\n\n    def __init__(self, alert_factor: float = 8.0):\n        self.alert_factor = alert_factor\n\n    def score(self, txn, holder, history):\n        factor = holder.deviation_factor(txn.amount)\n        s = min(factor / self.alert_factor, 1.0) if factor > 1 else 0.0\n        return RuleResult(self.name, round(s, 3),\n                          f"${txn.amount:,.2f} is {factor}x the ${holder.typical_amount:,.2f} baseline")'),
            ("Implement the unusual-hour and high-risk-category rules",
             'class UnusualHourRule(FraudRule):\n    """Flags activity outside the cardholder\'s normal waking window."""\n    weight = 0.6\n\n    def score(self, txn, holder, history):\n        s = 0.8 if txn.hour in {0, 1, 2, 3, 4, 5} else 0.0\n        return RuleResult(self.name, s, f"transaction at {txn.hour:02d}:00")\n\nclass HighRiskCategoryRule(FraudRule):\n    """Flags merchant categories with elevated chargeback rates."""\n    weight = 0.8\n\n    RISK = {"crypto_exchange": 0.9, "gift_cards": 0.8,\n            "jewellery": 0.6, "online_gaming": 0.5}\n\n    def score(self, txn, holder, history):\n        s = self.RISK.get(txn.merchant_category, 0.0)\n        return RuleResult(self.name, s, f"category {txn.merchant_category}")'),
            ("Implement the velocity rule — it needs history, which the shared interface already provides",
             'from datetime import timedelta\n\nclass VelocityRule(FraudRule):\n    """Flags many transactions inside a short window."""\n    weight = 1.5\n\n    def __init__(self, window_minutes: int = 10, threshold: int = 4):\n        self.window = timedelta(minutes=window_minutes)\n        self.threshold = threshold\n\n    def score(self, txn, holder, history):\n        recent = [h for h in history\n                  if 0 <= (txn.ts - h.ts).total_seconds() <= self.window.total_seconds()]\n        n = len(recent) + 1\n        s = min((n - 1) / self.threshold, 1.0) if n > 1 else 0.0\n        return RuleResult(self.name, round(s, 3),\n                          f"{n} transactions in {self.window.seconds // 60} minutes")'),
            ("Call every rule through the SAME interface — this is polymorphism doing real work",
             'uv run python -c "\nimport sqlite3\nfrom models import Transaction\nfrom cardholder import Cardholder\nfrom rules import AmountDeviationRule, UnusualHourRule, HighRiskCategoryRule, VelocityRule\ncon = sqlite3.connect(\'cardguard.db\')\nrow = con.execute(\'SELECT * FROM transactions WHERE is_known_fraud=1 ORDER BY amount DESC LIMIT 1\').fetchone()\ntxn = Transaction.from_row(row)\nchr_ = con.execute(\'SELECT card_ref,name,home_city,typical_amount FROM cardholders WHERE card_ref=?\', (txn.card_ref,)).fetchone()\nholder = Cardholder(*chr_)\nrules = [AmountDeviationRule(), UnusualHourRule(), HighRiskCategoryRule(), VelocityRule()]\nprint(txn)\nfor r in rules:\n    res = r.score(txn, holder, [])\n    print(f\'  {res.rule_name:<24} {res.score:>5}  {res.reason}\')\n"'),
            ("Note what inheritance bought: adding a fifth rule requires no change to any caller."),
        ],
        test="FraudRule cannot be instantiated; all four rules implement score() and return a RuleResult; a known-fraud transaction produces non-zero scores from the relevant rules.",
    ),
    dict(
        num=8,
        topic=2,
        title="Compose Rules into an Engine",
        objective="Use composition to assemble behaviour from independent parts",
        desc="The learner builds a RuleEngine that HAS-A list of rules rather than inheriting from any of them, producing a weighted composite score with a full explanation of every contributing rule.",
        build="A RuleEngine returning a ScreeningResult with a composite score and per-rule reasons",
        services="uv, Python 3.12",
        steps=[
            ("Write the engine — note it inherits from nothing; it composes",
             '# engine.py\nfrom dataclasses import dataclass, field\nfrom models import Transaction\nfrom cardholder import Cardholder\nfrom rules import FraudRule, RuleResult\n\n@dataclass\nclass ScreeningResult:\n    """The engine\'s decision, with every reason that produced it."""\n    txn_id: int\n    card_ref: str\n    composite_score: float\n    flagged: bool\n    results: list[RuleResult] = field(default_factory=list)\n\n    def explain(self) -> str:\n        head = (f"Transaction {self.txn_id} ({self.card_ref}): "\n                f"score {self.composite_score} "\n                f"{\'FLAGGED\' if self.flagged else \'clean\'}")\n        lines = [f"    - {r.rule_name} {r.score} :: {r.reason}"\n                 for r in self.results if r.score > 0]\n        return "\\n".join([head, *lines])'),
            ("Add the engine itself",
             'class RuleEngine:\n    """Composes independent rules into one weighted decision."""\n\n    def __init__(self, rules: list[FraudRule], threshold: float = 0.55):\n        if not rules:\n            raise ValueError("at least one rule is required")\n        self.rules = rules\n        self.threshold = threshold\n\n    def screen(self, txn: Transaction, holder: Cardholder,\n               history: list[Transaction]) -> ScreeningResult:\n        results = [r.score(txn, holder, history) for r in self.rules]\n        total_weight = sum(r.weight for r in self.rules)\n        composite = sum(res.score * rule.weight\n                        for res, rule in zip(results, self.rules)) / total_weight\n        composite = round(composite, 3)\n        return ScreeningResult(txn.id, txn.card_ref, composite,\n                               composite >= self.threshold, results)'),
            ("Screen a known-fraud transaction and read the explanation",
             'uv run python -c "\nimport sqlite3\nfrom models import Transaction\nfrom cardholder import Cardholder\nfrom rules import AmountDeviationRule, UnusualHourRule, HighRiskCategoryRule, VelocityRule\nfrom engine import RuleEngine\ncon = sqlite3.connect(\'cardguard.db\')\nrow = con.execute(\'SELECT * FROM transactions WHERE is_known_fraud=1 ORDER BY amount DESC LIMIT 1\').fetchone()\ntxn = Transaction.from_row(row)\nholder = Cardholder(*con.execute(\'SELECT card_ref,name,home_city,typical_amount FROM cardholders WHERE card_ref=?\',(txn.card_ref,)).fetchone())\neng = RuleEngine([AmountDeviationRule(), UnusualHourRule(), HighRiskCategoryRule(), VelocityRule()])\nprint(eng.screen(txn, holder, []).explain())\n"'),
            ("Screen a normal transaction and confirm it stays clean",
             'uv run python -c "\nimport sqlite3\nfrom models import Transaction\nfrom cardholder import Cardholder\nfrom rules import AmountDeviationRule, UnusualHourRule, HighRiskCategoryRule, VelocityRule\nfrom engine import RuleEngine\ncon = sqlite3.connect(\'cardguard.db\')\nrow = con.execute(\"SELECT * FROM transactions WHERE is_known_fraud=0 AND merchant_category=\'grocery\' LIMIT 1\").fetchone()\ntxn = Transaction.from_row(row)\nholder = Cardholder(*con.execute(\'SELECT card_ref,name,home_city,typical_amount FROM cardholders WHERE card_ref=?\',(txn.card_ref,)).fetchone())\neng = RuleEngine([AmountDeviationRule(), UnusualHourRule(), HighRiskCategoryRule(), VelocityRule()])\nprint(eng.screen(txn, holder, []).explain())\n"'),
            ("Reconfigure the engine WITHOUT touching any rule class — composition in action",
             'uv run python -c "\nfrom rules import AmountDeviationRule, HighRiskCategoryRule\nfrom engine import RuleEngine\nstrict = RuleEngine([AmountDeviationRule(alert_factor=4.0), HighRiskCategoryRule()], threshold=0.35)\nprint(\'rules:\', [r.name for r in strict.rules], \'threshold:\', strict.threshold)\n"'),
            ("Ask your AI assistant to add a fifth rule and confirm the engine needs no edit",
             "Ask the assistant: Add a RoundAmountRule to rules.py that subclasses FraudRule with weight 0.4 and returns score 0.5 when the transaction amount is an exact multiple of 100, since round-number testing charges are a common card-testing signal. Do not modify RuleEngine."),
            ("Note the design principle: inheritance shares WHAT rules are; composition decides WHICH rules run."),
        ],
        test="The engine flags the known-fraud transaction with a readable explanation, leaves a grocery transaction clean, and can be reconfigured with different rules and thresholds without editing any rule class.",
    ),
]
