"""
TOPIC 5 — Packaging and Deployment
Streamlit UI · Configuration · uv Lockfiles · Docker · Verified Deployment

Completes the three-tier application: Streamlit (UI) -> FastAPI (service)
-> SQLite (persistence), built on Topics 1-4.
"""

TOPIC5 = [
    dict(
        num=17,
        topic=5,
        title="Build a Fraud Analyst Dashboard with Streamlit",
        objective="Create a data application UI that consumes the API",
        desc="The learner builds the third tier: a Streamlit dashboard a fraud analyst actually uses — review queue, screening form and trend charts — calling the FastAPI service rather than reaching into the database.",
        build="A running Streamlit dashboard with live screening, a review queue and charts",
        services="uv, Streamlit, FastAPI, httpx, pandas",
        steps=[
            ("Add Streamlit", "uv add streamlit httpx"),
            ("Build the dashboard shell and the live screening form",
             '# app.py\nimport httpx\nimport pandas as pd\nimport streamlit as st\n\nAPI = st.secrets.get("api_url", "http://127.0.0.1:8000")\n\nst.set_page_config(page_title="CardGuard", page_icon="\\U0001F6E1", layout="wide")\nst.title("CardGuard — Fraud Screening Console")\n\nwith st.sidebar:\n    st.header("Screen a transaction")\n    card_ref = st.text_input("Card reference", "CH0001")\n    amount = st.number_input("Amount (SGD)", min_value=0.01, value=86.40, step=10.0)\n    category = st.selectbox("Merchant category",\n        ["grocery","fuel","restaurant","electronics","online_gaming",\n         "jewellery","crypto_exchange","gift_cards","pharmacy","transport"])\n    hour = st.slider("Hour of day", 0, 23, 10)\n    submitted = st.button("Screen", type="primary")\n\nif submitted:\n    payload = {"card_ref": card_ref, "ts": f"2026-04-15T{hour:02d}:30:00",\n               "amount": float(amount), "merchant_category": category,\n               "city": "Singapore", "lat": 1.3521, "lon": 103.8198}\n    try:\n        r = httpx.post(f"{API}/screen", json=payload, timeout=10)\n        r.raise_for_status()\n        out = r.json()\n    except httpx.HTTPStatusError as exc:\n        st.error(f"API rejected the request ({exc.response.status_code}): {exc.response.text}")\n    except httpx.RequestError:\n        st.error("Cannot reach the screening API. Is it running on port 8000?")\n    else:\n        colour = {"approve": "green", "review": "orange", "decline": "red"}[out["decision"]]\n        st.markdown(f"### Decision: :{colour}[{out[\'decision\'].upper()}]")\n        st.metric("Composite score", out["composite_score"])\n        if out["hits"]:\n            st.dataframe(pd.DataFrame(out["hits"]), width="stretch")\n        else:\n            st.info("No rule fired on this transaction.")'),
            ("Add the review queue and trend charts",
             '# app.py (add)\nst.divider()\nleft, right = st.columns([2, 1])\n\ntry:\n    rows = httpx.get(f"{API}/screenings", params={"limit": 200}, timeout=10).json()\n    stats = httpx.get(f"{API}/stats", timeout=10).json()\nexcept httpx.RequestError:\n    st.warning("API unavailable — showing no history.")\n    rows, stats = [], {}\n\nwith left:\n    st.subheader("Recent screenings")\n    if rows:\n        df = pd.DataFrame(rows)\n        df["screened_at"] = pd.to_datetime(df["screened_at"])\n        st.dataframe(\n            df[["card_ref","amount","merchant_category","composite_score","decision","screened_at"]],\n            width="stretch", height=340)\n    else:\n        st.info("No screenings yet — submit one from the sidebar.")\n\nwith right:\n    st.subheader("Decisions")\n    if stats:\n        st.bar_chart(pd.Series(stats, name="count"))\n        total = sum(stats.values())\n        flagged = stats.get("review", 0) + stats.get("decline", 0)\n        st.metric("Flag rate", f"{100 * flagged / total:.1f}%" if total else "—")'),
            ("Run both tiers — API in one terminal, UI in another",
             "# terminal 1\nuv run uvicorn main:app --reload --port 8000\n\n# terminal 2\nuv run streamlit run app.py"),
            ("Screen a normal transaction in the UI and watch it land in the queue", "open http://localhost:8501"),
            ("Screen a $5,000 jewellery charge at 02:00 and confirm it turns red"),
            ("Stop the API and confirm the UI degrades gracefully instead of crashing",
             "# stop uvicorn (Ctrl-C), then click Screen in the UI"),
            ("Note the architecture: the UI never touches SQLite. Swapping the database would not change app.py at all."),
        ],
        test="The dashboard screens transactions live, colour-codes decisions, lists the review queue and charts decision counts; with the API stopped it shows a clear error rather than a traceback.",
    ),
    dict(
        num=18,
        topic=5,
        title="Externalise Configuration and Protect Secrets",
        objective="Move settings out of code into the environment",
        desc="The learner replaces every hard-coded value with typed settings loaded from the environment, and ensures secrets can never be committed — the change that makes the same image runnable in dev and production.",
        build="A typed Settings object, a .env file and a .gitignore that excludes it",
        services="uv, pydantic-settings, python-dotenv",
        steps=[
            ("Find every hard-coded value in the project", "grep -rn '127.0.0.1\\|8000\\|cardguard.db\\|0.55\\|0.80' --include='*.py' . | grep -v '.venv'"),
            ("Add typed settings", "uv add pydantic-settings"),
            ("Declare configuration as a validated model",
             '# config.py\nfrom pydantic_settings import BaseSettings, SettingsConfigDict\n\nclass Settings(BaseSettings):\n    """All runtime configuration, validated at startup."""\n    model_config = SettingsConfigDict(env_file=".env", env_prefix="CARDGUARD_")\n\n    db_path: str = "cardguard.db"\n    api_url: str = "http://127.0.0.1:8000"\n    review_threshold: float = 0.55\n    decline_threshold: float = 0.80\n    velocity_window_minutes: int = 10\n    log_level: str = "INFO"\n\nsettings = Settings()'),
            ("Create .env for local development and EXCLUDE it from git immediately",
             '# .env\nCARDGUARD_DB_PATH=cardguard.db\nCARDGUARD_REVIEW_THRESHOLD=0.55\nCARDGUARD_DECLINE_THRESHOLD=0.80\nCARDGUARD_LOG_LEVEL=DEBUG'),
            ("Add the gitignore entries BEFORE the first commit",
             '# .gitignore\n.env\n.env.*\n!.env.example\n.venv/\n__pycache__/\n*.db\n.pytest_cache/'),
            ("Commit a .env.example instead, so a new joiner knows what to set",
             '# .env.example — safe to commit, contains no real values\nCARDGUARD_DB_PATH=cardguard.db\nCARDGUARD_REVIEW_THRESHOLD=0.55\nCARDGUARD_DECLINE_THRESHOLD=0.80\nCARDGUARD_LOG_LEVEL=INFO'),
            ("Replace the hard-coded thresholds with settings",
             '# main.py (replace decide())\nfrom config import settings\n\ndef decide(score: float) -> str:\n    if score >= settings.decline_threshold: return "decline"\n    if score >= settings.review_threshold:  return "review"\n    return "approve"'),
            ("Prove configuration is live — override without editing any code",
             'uv run python -c "\nfrom config import settings\nprint(\'default review threshold:\', settings.review_threshold)\n"\nCARDGUARD_REVIEW_THRESHOLD=0.30 uv run python -c "\nfrom config import settings\nprint(\'overridden by environment:\', settings.review_threshold)\n"'),
            ("Confirm .env is genuinely ignored", "git check-ignore -v .env && echo 'SAFE: .env will not be committed'"),
        ],
        test="Settings load from .env; an environment variable overrides them without a code change; git check-ignore confirms .env is excluded; .env.example is committed in its place.",
    ),
    dict(
        num=19,
        topic=5,
        title="Lock Dependencies and Containerise the API",
        objective="Package the application into a reproducible image",
        desc="The learner writes a multi-stage Dockerfile that installs from uv.lock, runs as a non-root user, and produces an image that behaves identically on any machine.",
        build="A built Docker image running the screening API with a health check",
        services="uv, Docker, uvicorn",
        steps=[
            ("Confirm the lockfile is current and committed", "uv lock --check\ngit add uv.lock pyproject.toml"),
            ("Write the Dockerfile — multi-stage keeps the final image small",
             '# Dockerfile\nFROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim AS builder\nWORKDIR /app\nENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy\n\n# Install dependencies first so this layer caches across code changes\nCOPY pyproject.toml uv.lock ./\nRUN uv sync --frozen --no-install-project --no-dev\n\nCOPY . .\nRUN uv sync --frozen --no-dev\n\nFROM python:3.12-slim-bookworm AS runtime\nRUN useradd --create-home --uid 1000 appuser\nWORKDIR /app\nCOPY --from=builder --chown=appuser:appuser /app /app\nENV PATH="/app/.venv/bin:$PATH" PYTHONUNBUFFERED=1\nUSER appuser\nEXPOSE 8000\nHEALTHCHECK --interval=30s --timeout=3s --retries=3 \\\\\n  CMD python -c "import httpx,sys; sys.exit(0 if httpx.get(\'http://127.0.0.1:8000/health\').status_code==200 else 1)"\nCMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]'),
            ("Exclude everything the image does not need",
             '# .dockerignore\n.venv/\n.git/\n.env\n*.db\n__pycache__/\n.pytest_cache/\ntests/\n*.md'),
            ("Build the image", "docker build -t cardguard-api:1.0 ."),
            ("Check the size — multi-stage should keep it well under 300MB", "docker images cardguard-api:1.0"),
            ("Run it, passing configuration as environment variables",
             "docker run -d --name cardguard \\\n  -p 8000:8000 \\\n  -e CARDGUARD_REVIEW_THRESHOLD=0.55 \\\n  -e CARDGUARD_LOG_LEVEL=INFO \\\n  -v \"$(pwd)/cardguard.db:/app/cardguard.db\" \\\n  cardguard-api:1.0"),
            ("Verify the container is healthy and answering",
             "docker ps --filter name=cardguard --format 'table {{.Names}}\\t{{.Status}}'\ncurl -s http://127.0.0.1:8000/health"),
            ("Screen a transaction against the CONTAINER, not your laptop's Python",
             'curl -s -X POST http://127.0.0.1:8000/screen -H "Content-Type: application/json" -d \'{"card_ref":"CH0023","ts":"2026-04-15T02:14:00","amount":5128.33,"merchant_category":"jewellery","city":"Singapore","lat":1.3521,"lon":103.8198}\' | python3 -m json.tool'),
            ("Read the logs and confirm it runs as a non-root user",
             "docker logs cardguard --tail 20\ndocker exec cardguard whoami"),
        ],
        test="The image builds, runs as appuser, reports healthy, and returns a decline decision for the fraud transaction posted to the container.",
    ),
    dict(
        num=20,
        topic=5,
        title="Deploy the Full Stack with Docker Compose",
        objective="Run and verify a multi-service application",
        desc="The learner composes the API and the Streamlit UI into one stack with a shared volume and dependency ordering, then verifies the deployment end to end — the final integration of everything built in Topics 1-5.",
        build="A running two-service stack verified with a real screening through the UI",
        services="Docker Compose, FastAPI, Streamlit, SQLite",
        steps=[
            ("Write a Dockerfile for the UI tier",
             '# Dockerfile.ui\nFROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim\nWORKDIR /app\nENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy\nCOPY pyproject.toml uv.lock ./\nRUN uv sync --frozen --no-dev\nCOPY . .\nENV PATH="/app/.venv/bin:$PATH"\nEXPOSE 8501\nCMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port=8501"]'),
            ("Compose the stack",
             '# compose.yaml\nservices:\n  api:\n    build: .\n    ports: ["8000:8000"]\n    environment:\n      CARDGUARD_DB_PATH: /data/cardguard.db\n      CARDGUARD_REVIEW_THRESHOLD: "0.55"\n      CARDGUARD_DECLINE_THRESHOLD: "0.80"\n    volumes: ["cardguard-data:/data"]\n    healthcheck:\n      test: ["CMD", "python", "-c", "import httpx,sys; sys.exit(0 if httpx.get(\'http://127.0.0.1:8000/health\').status_code==200 else 1)"]\n      interval: 10s\n      timeout: 3s\n      retries: 5\n\n  ui:\n    build:\n      context: .\n      dockerfile: Dockerfile.ui\n    ports: ["8501:8501"]\n    environment:\n      CARDGUARD_API_URL: http://api:8000\n    depends_on:\n      api:\n        condition: service_healthy\n\nvolumes:\n  cardguard-data:'),
            ("Point the UI at the service name — inside the network it is not localhost",
             '# app.py (replace the API constant)\nimport os\nAPI = os.getenv("CARDGUARD_API_URL", "http://127.0.0.1:8000")'),
            ("Bring the stack up", "docker compose up --build -d"),
            ("Confirm the UI waited for the API to become healthy",
             "docker compose ps\ndocker compose logs api --tail 5"),
            ("Seed the database inside the running container",
             "docker compose exec api python mockdata.py\ndocker compose exec api ls -la /data"),
            ("Verify end to end through the browser — screen a fraudulent charge in the UI",
             "open http://localhost:8501"),
            ("Verify the API tier independently",
             'curl -s http://127.0.0.1:8000/health\ncurl -s http://127.0.0.1:8000/stats | python3 -m json.tool'),
            ("Confirm data survives a restart — this is what the volume is for",
             "docker compose restart api\nsleep 5\ncurl -s http://127.0.0.1:8000/stats | python3 -m json.tool"),
            ("Tear down, keeping the data volume", "docker compose down\ndocker volume ls | grep cardguard"),
        ],
        test="Both services start, the UI waits for the API health check, a screening submitted in the browser is stored and visible via /stats, and the data survives a container restart.",
    ),
]
