"""
TOPIC 1 — Vibe Coding Foundations
uv Projects · AI Coding Assistants · Prompting Patterns · AI-Assisted Refactoring

Every lab standardises on uv. Labs are written against realistic mock data
generated locally, so they run offline and deterministically in a classroom.
"""

TOPIC1 = [
    dict(
        num=1,
        topic=1,
        title="Set Up a Reproducible Python Project with uv",
        objective="Create and run a Python project using uv",
        desc="The learner installs uv, creates a project, adds locked dependencies, and runs code through uv so the environment is identical on every machine. This is the foundation every later lab builds on.",
        build="A uv project with pyproject.toml, uv.lock and a working entry point",
        services="uv, Python 3.12, pyproject.toml, uv.lock",
        steps=[
            ("Confirm uv is installed and check the version", "uv --version"),
            ("Create a new project folder and initialise it", "uv init cardguard\ncd cardguard"),
            ("Inspect what uv generated — note pyproject.toml is the project manifest", "ls -a\ncat pyproject.toml"),
            ("Pin the Python version so every learner runs the same interpreter", "uv python pin 3.12"),
            ("Add a dependency — uv resolves, installs and writes uv.lock in one step", "uv add pandas"),
            ("Open uv.lock and observe the exact pinned versions", "head -30 uv.lock"),
            ("Write a first script that proves the dependency is importable",
             '# main.py\nimport pandas as pd\n\ndef main() -> None:\n    df = pd.DataFrame({"card": ["4111...1111", "5500...0004", "4111...1111"],\n                       "merchant": ["SG Grocer", "Overseas ATM", "SG Grocer"],\n                       "amount": [42.90, 800.00, 15.50]})\n    print(df)\n    print(f"Total screened: ${df[\'amount\'].sum():,.2f}")\n\nif __name__ == "__main__":\n    main()'),
            ("Run it through uv — no venv activation needed", "uv run python main.py"),
            ("Prove reproducibility: delete the venv and restore it from the lockfile", "rm -rf .venv\nuv sync\nuv run python main.py"),
        ],
        test="uv run python main.py prints the transaction DataFrame and the screened total. After deleting .venv, uv sync restores it and the script produces identical output.",
    ),
    dict(
        num=2,
        topic=1,
        title="Write Effective Prompts for an AI Coding Assistant",
        objective="Apply prompting patterns that produce correct, reviewable code",
        desc="The learner contrasts a vague prompt with a specified prompt on the same task, then applies the goal-constraints-inputs-output pattern to generate a function that handles real edge cases.",
        build="Two versions of a transaction risk-scoring function and a written comparison of the prompts that produced them",
        services="AI coding assistant (Claude / Copilot / Cursor), uv, Python",
        steps=[
            ("Start from the vague prompt and record exactly what you get back",
             "Ask the assistant: write a function to score a transaction"),
            ("Read the generated code critically — list what it assumed. Typical gaps: what counts as high value, whether an overseas merchant matters, what the score range is, what happens for a negative amount."),
            ("Rewrite the prompt using the four-part pattern — goal, constraints, inputs, expected output",
             "Ask the assistant: Write a Python function score_transaction(amount: float, is_overseas: bool, hour: int) -> dict that returns a risk score from 0 to 100 and the reasons that contributed to it. Add 40 points when the amount exceeds $500, 30 points when the merchant is overseas, and 20 points when the hour is between 1am and 5am. Cap the score at 100. Raise ValueError for a negative amount or an hour outside 0-23. Return the score and a list of reason strings."),
            ("Save the improved result and read every line before running it",
             '# scoring.py\ndef score_transaction(amount: float, is_overseas: bool, hour: int) -> dict:\n    """Return a 0-100 risk score for one transaction, with its reasons."""\n    if amount < 0:\n        raise ValueError("amount must not be negative")\n    if not 0 <= hour <= 23:\n        raise ValueError("hour must be between 0 and 23")\n\n    HIGH_VALUE = 500.00\n    score, reasons = 0, []\n\n    if amount > HIGH_VALUE:\n        score += 40\n        reasons.append("high value")\n    if is_overseas:\n        score += 30\n        reasons.append("overseas merchant")\n    if 1 <= hour <= 5:\n        score += 20\n        reasons.append("unusual hour")\n\n    return {"score": min(score, 100), "reasons": reasons}'),
            ("Test the boundaries the prompt specified — this is where generated code usually fails",
             'uv run python -c "\nfrom scoring import score_transaction\nprint(score_transaction(42.90, False, 14))   # low risk\nprint(score_transaction(800.00, True, 3))    # every rule fires\nprint(score_transaction(500.00, False, 14))  # exactly on the threshold\n"'),
            ("Confirm the error paths actually raise",
             'uv run python -c "\nfrom scoring import score_transaction\ntry:\n    score_transaction(-100, False, 14)\nexcept ValueError as e:\n    print(\'correctly raised:\', e)\n"'),
            ("Write two sentences in your notes: which prompt produced code you would ship, and why."),
        ],
        test="The specified prompt produces a function that caps the score at 100, fires each rule independently, and raises ValueError on invalid input. The learner can state why the vague prompt was insufficient.",
    ),
    dict(
        num=3,
        topic=1,
        title="Review and Correct AI-Generated Code",
        objective="Identify and fix defects in code produced by an AI assistant",
        desc="The learner is given a plausible but subtly wrong implementation, finds the defects by testing rather than by reading alone, and corrects them. This lab establishes that the developer, not the assistant, owns correctness.",
        build="A corrected discount calculator plus a short defect log",
        services="AI coding assistant, uv, Python",
        steps=[
            ("Save this generated function exactly as written — it looks reasonable",
             '# discount.py\ndef apply_discount(price, tier):\n    if tier == "gold":\n        return price * 0.8\n    elif tier == "silver":\n        return price * 0.9\n    elif tier == "bronze":\n        return price * 0.95\n    return price'),
            ("Probe it with the values a real order system would send",
             'uv run python -c "\nfrom discount import apply_discount\nprint(apply_discount(100, \'gold\'))\nprint(apply_discount(100, \'GOLD\'))\nprint(apply_discount(100, None))\nprint(apply_discount(-50, \'gold\'))\nprint(apply_discount(100.555, \'silver\'))\n"'),
            ("Record the defects you found: case sensitivity, no validation of price, unrounded currency, silent fallthrough on an unknown tier, and no type hints."),
            ("Ask the assistant to fix the specific defects — name them, do not say 'improve this'",
             "Ask the assistant: Fix these defects in apply_discount: (1) tier matching must be case-insensitive, (2) raise ValueError for a negative price, (3) raise ValueError for an unrecognised tier instead of silently returning the full price, (4) round the result to 2 decimal places, (5) add type hints and a docstring."),
            ("Review the corrected version line by line before accepting it",
             '# discount.py\nDISCOUNTS = {"gold": 0.20, "silver": 0.10, "bronze": 0.05}\n\ndef apply_discount(price: float, tier: str) -> float:\n    """Return the price after applying the tier discount."""\n    if price < 0:\n        raise ValueError("price must not be negative")\n    key = (tier or "").strip().lower()\n    if key not in DISCOUNTS:\n        raise ValueError(f"unknown tier: {tier!r}")\n    return round(price * (1 - DISCOUNTS[key]), 2)'),
            ("Re-run every probe that previously failed", 'uv run python -c "\nfrom discount import apply_discount\nprint(apply_discount(100, \'GOLD\'))\nprint(apply_discount(100.555, \'silver\'))\nfor bad in [(-50, \'gold\'), (100, \'platinum\'), (100, None)]:\n    try:\n        apply_discount(*bad)\n        print(\'NOT CAUGHT:\', bad)\n    except ValueError as e:\n        print(\'correctly raised:\', e)\n"'),
            ("Note the lesson: the first version ran without error on the happy path. Running is not the same as correct."),
        ],
        test="All five defects are fixed and demonstrated by tests. The learner can explain why reading alone did not reveal them.",
    ),
    dict(
        num=4,
        topic=1,
        title="Refactor Working Code Conversationally",
        objective="Use an AI assistant to restructure code without changing its behaviour",
        desc="The learner takes a working but poorly structured script, establishes a behavioural baseline, refactors it into small testable functions with AI assistance, and proves the output is unchanged.",
        build="A refactored sales summary script with an unchanged, verified output",
        services="AI coding assistant, uv, Python",
        steps=[
            ("Save the working script — it produces correct output but is one long block",
             '# sales_report.py\norders = [\n    {"id": 1, "region": "North", "amount": 1200.50, "status": "paid"},\n    {"id": 2, "region": "South", "amount": 890.00, "status": "paid"},\n    {"id": 3, "region": "North", "amount": 450.25, "status": "refunded"},\n    {"id": 4, "region": "East",  "amount": 2100.75, "status": "paid"},\n    {"id": 5, "region": "South", "amount": 310.00, "status": "pending"},\n]\n\ntotals = {}\nfor o in orders:\n    if o["status"] == "paid":\n        if o["region"] not in totals:\n            totals[o["region"]] = 0\n        totals[o["region"]] += o["amount"]\nfor r in sorted(totals):\n    print(f"{r}: ${totals[r]:,.2f}")\nprint(f"TOTAL: ${sum(totals.values()):,.2f}")'),
            ("Capture the baseline output to a file — this is the contract the refactor must preserve",
             "uv run python sales_report.py > baseline.txt\ncat baseline.txt"),
            ("Ask for a structural refactor and state explicitly that behaviour must not change",
             "Ask the assistant: Refactor sales_report.py into three functions — filter_paid(orders), total_by_region(orders) and format_report(totals) — plus a main() guarded by if __name__ == '__main__'. Add type hints. The printed output must be byte-for-byte identical to the current version."),
            ("Save the refactored version",
             '# sales_report.py\nfrom typing import Iterable\n\nOrder = dict[str, object]\n\nORDERS: list[Order] = [\n    {"id": 1, "region": "North", "amount": 1200.50, "status": "paid"},\n    {"id": 2, "region": "South", "amount": 890.00, "status": "paid"},\n    {"id": 3, "region": "North", "amount": 450.25, "status": "refunded"},\n    {"id": 4, "region": "East",  "amount": 2100.75, "status": "paid"},\n    {"id": 5, "region": "South", "amount": 310.00, "status": "pending"},\n]\n\ndef filter_paid(orders: Iterable[Order]) -> list[Order]:\n    """Return only the orders with status \'paid\'."""\n    return [o for o in orders if o["status"] == "paid"]\n\ndef total_by_region(orders: Iterable[Order]) -> dict[str, float]:\n    """Sum order amounts grouped by region."""\n    totals: dict[str, float] = {}\n    for o in orders:\n        region = str(o["region"])\n        totals[region] = totals.get(region, 0.0) + float(o["amount"])\n    return totals\n\ndef format_report(totals: dict[str, float]) -> str:\n    """Render the per-region totals and the grand total."""\n    lines = [f"{r}: ${totals[r]:,.2f}" for r in sorted(totals)]\n    lines.append(f"TOTAL: ${sum(totals.values()):,.2f}")\n    return "\\n".join(lines)\n\ndef main() -> None:\n    print(format_report(total_by_region(filter_paid(ORDERS))))\n\nif __name__ == "__main__":\n    main()'),
            ("Prove the behaviour is unchanged by diffing against the baseline",
             "uv run python sales_report.py > after.txt\ndiff baseline.txt after.txt && echo 'IDENTICAL — refactor is safe'"),
            ("Now that the logic is in functions, test one piece in isolation — impossible before the refactor",
             'uv run python -c "\nfrom sales_report import total_by_region\nrows = [{\'region\': \'North\', \'amount\': 100.0, \'status\': \'paid\'},\n        {\'region\': \'North\', \'amount\': 50.0,  \'status\': \'paid\'}]\nassert total_by_region(rows) == {\'North\': 150.0}\nprint(\'unit test passed\')\n"'),
            ("Note the sequence that makes refactoring safe: baseline first, refactor second, diff third."),
        ],
        test="diff reports no difference between baseline.txt and after.txt, and total_by_region can be unit-tested independently.",
    ),
]
