"""
TOPIC 3 — Data Analytics with pandas + Error Handling with Exceptions
DataFrames · Cleaning · GroupBy · Rolling Windows · Exceptions · Custom Errors

Domain: CardGuard fraud analytics over cardguard.db (10,851 transactions).
Verified on pandas 3.0 (Copy-on-Write is the default).
"""

TOPIC3 = [
    dict(
        num=9,
        topic=3,
        title="Load and Explore Transactions with pandas",
        objective="Read SQL into a DataFrame and profile it",
        desc="The learner loads the transaction table into pandas, inspects dtypes and null counts, and produces a first profile of spending — the step every analytics task starts with.",
        build="A loaded, correctly-typed transactions DataFrame plus a spend profile by category",
        services="uv, pandas 3.0, sqlite3",
        steps=[
            ("Add pandas and load the table", "uv add pandas\nuv run python -c \"\nimport sqlite3, pandas as pd\ncon = sqlite3.connect('cardguard.db')\ndf = pd.read_sql_query('SELECT * FROM transactions', con)\nprint(df.shape)\nprint(df.head())\n\""),
            ("Inspect dtypes — note ts arrived as text, not datetime",
             'uv run python -c "\nimport sqlite3, pandas as pd\ncon = sqlite3.connect(\'cardguard.db\')\ndf = pd.read_sql_query(\'SELECT * FROM transactions\', con)\nprint(df.dtypes)\nprint(df.isna().sum())\n"'),
            ("Write a loader that fixes the types once, so no downstream code has to",
             '# analytics.py\nimport sqlite3\nimport pandas as pd\n\ndef load_transactions(db_path: str = "cardguard.db") -> pd.DataFrame:\n    """Load transactions with correct dtypes."""\n    con = sqlite3.connect(db_path)\n    try:\n        df = pd.read_sql_query("SELECT * FROM transactions", con)\n    finally:\n        con.close()          # always closes, even if the query raises\n    df["ts"] = pd.to_datetime(df["ts"])\n    df["merchant_category"] = df["merchant_category"].astype("category")\n    df["hour"] = df["ts"].dt.hour\n    df["date"] = df["ts"].dt.date\n    return df'),
            ("Profile spend by merchant category — split-apply-combine",
             'uv run python -c "\nfrom analytics import load_transactions\ndf = load_transactions()\nprofile = (df.groupby(\'merchant_category\', observed=True)[\'amount\']\n             .agg([\'count\', \'sum\', \'mean\', \'max\']).round(2)\n             .sort_values(\'sum\', ascending=False))\nprint(profile)\n"'),
            ("Answer a real business question: which hours carry the most spend?",
             'uv run python -c "\nfrom analytics import load_transactions\ndf = load_transactions()\nby_hour = df.groupby(\'hour\')[\'amount\'].agg([\'count\',\'sum\']).round(2)\nprint(by_hour.tail(8))\nprint(\'\\novernight share:\', round(100*df[df.hour<6][\'amount\'].sum()/df[\'amount\'].sum(),2), \'%\')\n"'),
            ("See the pandas 3.0 Copy-on-Write behaviour that AI assistants get wrong",
             'uv run python -c "\nimport pandas as pd\ndf = pd.DataFrame({\'a\':[1,2,3],\'b\':[10,20,30]})\n# The pandas 1.x idiom an assistant will often generate:\ndf[df.a > 1][\'b\'] = 0\nprint(df)   # unchanged under Copy-on-Write — the write went to a temporary\n# The correct form:\ndf.loc[df.a > 1, \'b\'] = 0\nprint(df)\n"'),
            ("Note the lesson: verify generated pandas against your installed version, not against a tutorial."),
        ],
        test="load_transactions returns 10,851 rows with ts as datetime64; the category profile and hourly breakdown print; the learner can state why chained assignment silently fails.",
    ),
    dict(
        num=10,
        topic=3,
        title="Handle Errors with Exceptions",
        objective="Use try/except/else/finally and raise meaningful custom exceptions",
        desc="The learner makes the loader robust: catching the specific failures that actually occur, defining a custom exception hierarchy for the domain, and guaranteeing cleanup with finally. A screening service that crashes on one bad row fails open — this lab prevents that.",
        build="A domain exception hierarchy plus a validated, fail-safe loader",
        services="uv, pandas, sqlite3, Python exceptions",
        steps=[
            ("Define exceptions that describe the DOMAIN, not the plumbing",
             '# errors.py\nclass CardGuardError(Exception):\n    """Base class for every CardGuard failure — callers can catch this one type."""\n\nclass DataSourceError(CardGuardError):\n    """The transaction store could not be read."""\n\nclass ValidationError(CardGuardError):\n    """A transaction failed validation before scoring."""\n    def __init__(self, field: str, value, message: str):\n        self.field, self.value = field, value\n        super().__init__(f"{field}={value!r}: {message}")\n\nclass RuleExecutionError(CardGuardError):\n    """A scoring rule raised while screening a transaction."""'),
            ("Catch the SPECIFIC errors that happen, and translate them to domain errors",
             '# analytics.py (updated)\nimport sqlite3\nfrom pathlib import Path\nimport pandas as pd\nfrom errors import DataSourceError\n\ndef load_transactions(db_path: str = "cardguard.db") -> pd.DataFrame:\n    """Load transactions, raising DataSourceError on any read failure."""\n    if not Path(db_path).exists():\n        raise DataSourceError(f"database not found: {db_path}")\n    con = None\n    try:\n        con = sqlite3.connect(db_path)\n        df = pd.read_sql_query("SELECT * FROM transactions", con)\n    except sqlite3.DatabaseError as exc:\n        raise DataSourceError(f"could not read {db_path}: {exc}") from exc\n    else:\n        df["ts"] = pd.to_datetime(df["ts"])\n        df["hour"] = df["ts"].dt.hour\n        return df\n    finally:\n        if con is not None:\n            con.close()      # runs on success AND on failure'),
            ("Prove each failure path raises the right domain error",
             'uv run python -c "\nfrom analytics import load_transactions\nfrom errors import DataSourceError\ntry:\n    load_transactions(\'no_such.db\')\nexcept DataSourceError as e:\n    print(\'missing file ->\', e)\nopen(\'corrupt.db\',\'wb\').write(b\'not a database at all\')\ntry:\n    load_transactions(\'corrupt.db\')\nexcept DataSourceError as e:\n    print(\'corrupt file ->\', type(e).__name__)\n"'),
            ("Validate a transaction and raise ValidationError carrying the offending field",
             '# validate.py\nfrom errors import ValidationError\n\nVALID_CATEGORIES = {"grocery","fuel","restaurant","electronics","online_gaming",\n                    "jewellery","crypto_exchange","gift_cards","pharmacy","transport"}\n\ndef validate_txn(record: dict) -> dict:\n    """Raise ValidationError on the first problem found."""\n    amount = record.get("amount")\n    if amount is None:\n        raise ValidationError("amount", amount, "is required")\n    if not isinstance(amount, (int, float)):\n        raise ValidationError("amount", amount, "must be numeric")\n    if amount <= 0:\n        raise ValidationError("amount", amount, "must be positive")\n    if amount > 1_000_000:\n        raise ValidationError("amount", amount, "exceeds the maximum single charge")\n    cat = record.get("merchant_category")\n    if cat not in VALID_CATEGORIES:\n        raise ValidationError("merchant_category", cat, "is not a known category")\n    return record'),
            ("Run a batch where some records are bad — the batch must NOT die on the first failure",
             'uv run python -c "\nfrom validate import validate_txn\nfrom errors import ValidationError\nbatch = [\n  {\'amount\': 120.0, \'merchant_category\': \'grocery\'},\n  {\'amount\': -5.0,  \'merchant_category\': \'fuel\'},\n  {\'amount\': \'abc\', \'merchant_category\': \'grocery\'},\n  {\'amount\': 90.0,  \'merchant_category\': \'casino\'},\n  {\'amount\': 45.0,  \'merchant_category\': \'transport\'},\n]\nok, rejected = [], []\nfor i, rec in enumerate(batch):\n    try:\n        ok.append(validate_txn(rec))\n    except ValidationError as e:\n        rejected.append((i, str(e)))\nprint(f\'accepted {len(ok)}, rejected {len(rejected)}\')\nfor i, msg in rejected:\n    print(f\'  row {i}: {msg}\')\n"'),
            ("Contrast with the anti-pattern — a bare except hides the bug you needed to see",
             'uv run python -c "\n# ANTI-PATTERN: never do this\ntry:\n    result = 1 / 0\nexcept:              # catches everything, including typos and KeyboardInterrupt\n    result = 0\nprint(\'silently wrong:\', result)\n\n# Correct: name the exception you expect and can handle\ntry:\n    result = 1 / 0\nexcept ZeroDivisionError as e:\n    print(\'handled explicitly:\', e)\n"'),
            ("Ask your assistant to add a rule-level guard so one broken rule cannot stop a screen",
             "Ask the assistant: In RuleEngine.screen, wrap each rule call in try/except so that if one rule raises, the engine records a RuleExecutionError message on the result and continues scoring with the remaining rules. Never use a bare except."),
        ],
        test="Missing and corrupt databases raise DataSourceError; the 5-record batch accepts 2 and rejects 3 with field-level messages; the learner can explain why bare except is unsafe.",
    ),
    dict(
        num=11,
        topic=3,
        title="Build Per-Cardholder Baselines with GroupBy",
        objective="Compute per-group statistics with split-apply-combine",
        desc="The learner computes each cardholder's own spending baseline and deviation for every transaction — the statistical foundation the AmountDeviationRule needs, done for 40 cardholders at once instead of one at a time.",
        build="A per-cardholder baseline table and a deviation column on every transaction",
        services="uv, pandas 3.0",
        steps=[
            ("Compute one baseline per cardholder",
             'uv run python -c "\nfrom analytics import load_transactions\ndf = load_transactions()\nbase = df.groupby(\'card_ref\')[\'amount\'].agg([\'count\',\'mean\',\'median\',\'std\']).round(2)\nprint(base.head())\nprint(\'cardholders:\', len(base))\n"'),
            ("Join each transaction to its cardholder baseline with transform — same shape as the original",
             '# analytics.py (add)\ndef add_deviation(df):\n    """Attach each transaction\'s deviation from its own cardholder baseline."""\n    df = df.copy()\n    df["baseline"] = df.groupby("card_ref")["amount"].transform("median")\n    df["dev_factor"] = (df["amount"] / df["baseline"]).round(2)\n    return df'),
            ("Find the biggest deviations and check them against the seeded fraud flag",
             'uv run python -c "\nfrom analytics import load_transactions, add_deviation\ndf = add_deviation(load_transactions())\ntop = df.nlargest(10, \'dev_factor\')[[\'id\',\'card_ref\',\'amount\',\'baseline\',\'dev_factor\',\'merchant_category\',\'is_known_fraud\']]\nprint(top.to_string(index=False))\nprint(\'\\nof the top 10 deviations,\', int(top.is_known_fraud.sum()), \'are seeded fraud\')\n"'),
            ("Measure how well deviation alone separates fraud from normal",
             'uv run python -c "\nfrom analytics import load_transactions, add_deviation\ndf = add_deviation(load_transactions())\nprint(df.groupby(\'is_known_fraud\')[\'dev_factor\'].describe().round(2)[[\'count\',\'mean\',\'50%\',\'max\']])\n"'),
            ("Use median not mean for the baseline — prove why with an outlier",
             'uv run python -c "\nimport pandas as pd\ns = pd.Series([100,110,95,105,20000])\nprint(\'mean  \', round(s.mean(),2), \'<- dragged up by the fraud itself\')\nprint(\'median\', round(s.median(),2), \'<- robust to the outlier\')\n"'),
            ("Note the analytics lesson: the statistic you choose changes what you can detect."),
        ],
        test="Baselines compute for all 40 cardholders; dev_factor is attached to every row; the top deviations are dominated by seeded fraud; the learner can justify median over mean.",
    ),
    dict(
        num=12,
        topic=3,
        title="Detect Velocity Bursts with Rolling Time Windows",
        objective="Analyse ordered time-series data per group",
        desc="The learner sorts transactions per cardholder and counts how many occur inside a rolling 10-minute window — the history the VelocityRule needs, which cannot be computed one transaction at a time.",
        build="A txn_count_10min column plus the burst transactions it exposes",
        services="uv, pandas 3.0, rolling windows",
        steps=[
            ("Sort by cardholder and time — order is a precondition for any window function",
             '# analytics.py (add)\ndef add_velocity(df, window: str = "10min"):\n    """Count transactions per cardholder inside a rolling time window."""\n    df = df.sort_values(["card_ref", "ts"]).copy()\n    counts = (df.set_index("ts")\n                .groupby("card_ref")["amount"]\n                .rolling(window).count()\n                .reset_index(name="txn_count_10min"))\n    df = df.merge(counts, on=["card_ref", "ts"], how="left")\n    return df'),
            ("Find the bursts",
             'uv run python -c "\nfrom analytics import load_transactions, add_velocity\ndf = add_velocity(load_transactions())\nbursts = df[df.txn_count_10min >= 4]\nprint(\'burst transactions:\', len(bursts))\nprint(bursts[[\'card_ref\',\'ts\',\'amount\',\'merchant_category\',\'txn_count_10min\',\'is_known_fraud\']].head(12).to_string(index=False))\n"'),
            ("Check the hit rate of velocity as a signal on its own",
             'uv run python -c "\nfrom analytics import load_transactions, add_velocity\ndf = add_velocity(load_transactions())\nb = df[df.txn_count_10min >= 4]\nprint(f\'{int(b.is_known_fraud.sum())} of {len(b)} burst transactions are seeded fraud\')\nprint(\'precision:\', round(100*b.is_known_fraud.mean(),1), \'%\')\n"'),
            ("Inspect one full burst to see the pattern a fraudster leaves",
             'uv run python -c "\nfrom analytics import load_transactions, add_velocity\ndf = add_velocity(load_transactions())\ncard = df[df.txn_count_10min >= 5].card_ref.iloc[0]\nwin = df[df.card_ref == card].nlargest(8, \'txn_count_10min\')[[\'ts\',\'amount\',\'merchant_category\',\'txn_count_10min\']]\nprint(f\'card {card}\'); print(win.sort_values(\'ts\').to_string(index=False))\n"'),
            ("Compute the geographic-impossibility signal the engine is still missing",
             '# analytics.py (add)\nimport numpy as np\n\ndef add_geo_velocity(df):\n    """Implied travel speed (km/h) between consecutive transactions."""\n    df = df.sort_values(["card_ref", "ts"]).copy()\n    g = df.groupby("card_ref")\n    lat1, lon1 = np.radians(g["lat"].shift()), np.radians(g["lon"].shift())\n    lat2, lon2 = np.radians(df["lat"]), np.radians(df["lon"])\n    dlat, dlon = lat2 - lat1, lon2 - lon1\n    a = np.sin(dlat/2)**2 + np.cos(lat1)*np.cos(lat2)*np.sin(dlon/2)**2\n    km = 6371 * 2 * np.arcsin(np.sqrt(a))\n    hours = g["ts"].diff().dt.total_seconds() / 3600\n    df["implied_kmh"] = (km / hours.replace(0, np.nan)).round(1)\n    return df'),
            ("Find the physically impossible journeys",
             'uv run python -c "\nfrom analytics import load_transactions, add_geo_velocity\ndf = add_geo_velocity(load_transactions())\nimp = df[df.implied_kmh > 1000]\nprint(\'impossible journeys:\', len(imp))\nprint(imp[[\'card_ref\',\'ts\',\'city\',\'amount\',\'implied_kmh\',\'is_known_fraud\']].to_string(index=False))\n"'),
            ("Note: velocity and geography are only visible ACROSS rows. Row-at-a-time scoring cannot see them."),
        ],
        test="Velocity bursts and impossible journeys are both detected, dominated by seeded fraud, and the learner can explain why these signals require sorted per-group windows.",
    ),
]
